---
- name: Install python2-pip and setuptools for ansible
  become: true
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
    - python-setuptools

- name: Install enchant
  become: true
  package:
    name: enchant
    state: present

- name: Add universe repository for ubuntu
  become: true
  apt_repository:
    repo: >-
        deb http://archive.ubuntu.com/ubuntu
        {{ ansible_distribution_release|lower }} universe
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install venv for Debian
  become: true
  package:
    name: python3-venv
  when:
    - ansible_os_family == 'Debian'
    - sopel_install_python3

- name: Add sopel system user
  become: true
  user:
    name: sopel
    password: '!'
    home: '{{ sopel_install_dir }}'
    system: true
    state: present

- name: Make sopel folders
  become: true
  file:
    path: '{{ item }}'
    owner: sopel
    group: sopel
    state: directory
  with_items:
    - '{{ sopel_config_dir }}'
    - '{{ sopel_log_dir }}'
    - '{{ sopel_pid_dir }}'

- name: Copy sopel config
  become: true
  template:
    owner: sopel
    group: sopel
    src: templates/sopel.cfg.j2
    dest: '{{ sopel_config_dir }}/sopel.cfg'
  notify: restart sopel

- name: Add sopel systemd service
  become: true
  template:
    owner: sopel
    group: sopel
    src: templates/sopel.service.j2
    dest: /etc/systemd/system/sopel.service
  when: sopel_install_systemd_service

- name: Install sopel RedHat
  pip:
    name: [pip>19, setuptools>40, sopel>6]
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: '/usr/bin/python3.6 -m venv'
  when: ansible_os_family == 'RedHat'

- name: Install sopel Debian/Ubuntu legacy (1/3) (pip/setuptools)
  pip:
    name: ['pip>18,<19', setuptools>40]
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: /usr/bin/python3 -m venv
  when: (ansible_distribution == 'Ubuntu' and
        ansible_distribution_version|float <= 16.10) or
        (ansible_distribution == 'Debian' and
        ansible_distribution_version|int <= 8)

- name: Instal sopel Debian legacy (2/3) (iPython)
  pip:
    name: 'ipython==6.5'
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: /usr/bin/python3 -m venv
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_version|int <= 8

- name: Instal sopel Ubuntu legacy (2/3) (iPython)
  pip:
    name: 'ipython==7.2'
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: /usr/bin/python3 -m venv
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version|float <= 16.10

- name: Install sopel Debian/Ubuntu legacy (3/3) (Sopel)
  pip:
    name: 'sopel'
    state: present
    extra_args: '--no-binary sopel,pyenchant,maxminddb,simplegeneric'
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: /usr/bin/python3 -m venv
  when: (ansible_distribution == 'Ubuntu' and
        ansible_distribution_version|float <= 16.10) or
        (ansible_distribution == 'Debian' and
        ansible_distribution_version|int <= 8)

- name: Install sopel Debian
  environment:
    LC_ALL: 'en_US.UTF-8'
  pip:
    name: [pip>19, setuptools>40, sopel>6]
    state: present
    virtualenv: '{{ sopel_install_dir }}/venv'
    virtualenv_command: /usr/bin/python3 -m venv
  when: (ansible_distribution == 'Ubuntu' and
        ansible_distribution_version|float > 16.10) or
        (ansible_distribution == 'Debian' and
        ansible_distribution_version|int > 8)

- name: Start and enable sopel
  become: true
  service:
    name: sopel
    state: started
    enabled: true
  when: sopel_install_systemd_service

- name: Start and enable sopel
  become: true
  service:
    name: sopel
    state: started
  when:
    - sopel_start_systemd_service
    - sopel_install_systemd_service
